{{- if and .Values.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
stringData:
  {{ .Values.auth.secretKeys.rootPasswordKey }}: {{ .Values.auth.rootPassword | quote }}
  {{- if .Values.auth.username }}
  {{ .Values.auth.secretKeys.userPasswordKey }}: {{ .Values.auth.password | quote }}
  {{- end }}
{{- end }}

